# -*- coding: utf-8 -*-
"""Clases_y_Objetos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vXCm-n2-5bAPEznOeuRJLvBchSJs_rGT
"""

p1 = {
  'nombre' : "Diego",
  'edad' : 12,
  'vive' : True
}
p2 = {
  'nombre' : "Josefa",
  'edad' : 82,
  'vive' : True
}

x = {
    'modelo': 2025,
    'cc': 5000,
    'marca': 'CAT'
}



print(p1)

class Pastel():
  # contructor
  def __init__(self):
    self.forma = 'cuadrado'
    self.peso = 1
    self.sabor = 'chocolate'
    self.valor = 60000
    self.ingredientes = ['harina', 'huevos']

# Creacion de Objetos
pastel_1 = Pastel()

print(pastel_1.forma, pastel_1.peso, pastel_1.sabor, pastel_1.valor, pastel_1.ingredientes)

pastel_1.forma = 'redondo'
pastel_1.peso = 1
pastel_1.sabor = 'uva'
pastel_1.valor = 100000
pastel_1.ingredientes = ['harina', 'azucar', 'leche', 'uva']


pastel_2 = Pastel()
pastel_3 = Pastel()
print(pastel_1.forma, pastel_1.peso, pastel_1.sabor, pastel_1.valor, pastel_1.ingredientes)
print(pastel_2.forma, pastel_2.peso, pastel_2.sabor, pastel_2.valor, pastel_2.ingredientes)
print(pastel_3.forma, pastel_3.peso, pastel_3.sabor, pastel_3.valor, pastel_3.ingredientes)

# Creacion de la clase Vehiculo
class Vehiculo():
  def __init__(self):
    self.marca = ''
    self.modelo = ''
    self.cc = ''
    self.valor = 0

# Creacion de los objetos  de Vehiculo
c1 = Vehiculo()
c2 = Vehiculo()

# Modificar datos del Objeto c1
c1.marca = 'Subaru'
c1.modelo = 'Impreza'
c1.cc = 2000
c1.valor = 1000000

# Modificar datos del Objeto c2
c2.marca = 'Kia'
c2.modelo = 'Rio'
c2.cc = 1400
c2.valor = 20000

# Mostrar los valore Modificados
print(c1.marca, c1.modelo, c1.cc, c1.valor)
print(c2.marca, c2.modelo, c2.cc, c2.valor)

class Moto():
  # Constructor por valor
  def __init__(self, marca, modelo, cc, valor):
    self.marca = marca
    self.modelo = modelo
    self.cc = cc
    self.valor = valor
    self.velocidad = 0
    self.encendido = 'apagado'

  def encender(self):
    self.encendido = 'encendido'

  def apagar(self):
    self.encendido = 'apagado'

  def acelerar(self):
    self.velocidad = self.velocidad + 10



m1 = Moto('Yamaha', 'R1', 1000, 120000000)
m2 = Moto('Kawasaki', 'H2', 1000, 250000000)

m1.encender()
print(m1.marca, m1.modelo, m1.cc, m1.valor , m1.encendido, m1.velocidad )
for i in range(10):
  m1.acelerar()
  print(m1.marca, m1.modelo, m1.cc, m1.valor , m1.encendido, m1.velocidad )

m1.apagar()

print(m1.marca, m1.modelo, m1.cc, m1.valor , m1.encendido )
print(m2.marca, m2.modelo, m2.cc, m2.valor , m2.encendido)